### ISSUE TITLE
OpenCV Error

### ISSUE THREAD

**Issue by emartchenko** [mcserep/railroad#2]
Hello there, we are trying to use this project to identify railroads but continually run into OpenCV errors whether with LAS or LAZ files. We've tried a couple different files of each format but see the same error. Screenshots of trace provided below, any insights would be helpful. Thank you.

Running on LAZ file:
![image](https://user-images.githubusercontent.com/29958717/146089506-f25f1115-76e9-4a2a-98cb-0fea719291aa.png)

Running on LAS file:

![image](https://user-images.githubusercontent.com/29958717/146089163-1fe02433-cac4-480f-97c6-3ba7b8e1928d.png)

**Comment by Aladgit** [comment]
Has this bug already been fixed? I'm also running into several errors.

**Comment by mcserep** [comment]
Thanks for reporting this issue. The source of the error is that the algorithm failed to find the rail tracks. While in OpenCV3 there is no error in that case, in OpenCV2 an assertion fails upon writing a 0x0 size image.
We have made improvements on this and meanwhile switched to OpenCV4, so please try it again with a higher OpenCV version.

Of course, the real issue here is that the rail track was not found. I have 2 suggestions for that:
- Try to crop the railway and its close surroundings from the point cloud. Some terrain and vegetation nearby can be handled by the algorithm, but larger areas could "mislead" the algorithm and in the end no rail track is found.
- To avoid manual preprocessing of the data in such way, we have implemented a combined cable and rail track segmentation approach, by first locating the overhead cables and automatically cropping the point cloud based on its position, so the rail tracks can be found with much better results. This was implemented in cc1844222354dec3fe53612d583257e1913aea9b. See the [Usage Guide](https://github.com/mcserep/railroad/blob/master/USAGE.md#combined-detection) as a reference on how to use it.
